insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (1, 'Zoo', 69, 92, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (2, 'Zoo', 24, 58, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (3, 'Night Tour', 40, 90, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (4, 'Zoo', 27, 57, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (5, 'Zoo', 67, 58, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (6, 'Safari', 78, 41, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (7, 'Movie', 89, 86, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (8, 'Movie', 22, 90, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (9, 'Night Tour', 94, 63, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (10, 'Kids', 40, 19, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (11, 'Movie', 68, 49, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (12, 'Night Tour', 25, 97, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (13, 'Safari', 47, 44, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (14, 'Safari', 41, 23, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (15, 'Night Tour', 43, 43, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (16, 'Safari', 59, 85, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (17, 'Kids', 62, 70, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (18, 'Movie', 100, 32, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (19, 'Night Tour', 86, 12, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (20, 'Zoo', 48, 18, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (21, 'Zoo', 68, 13, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (22, 'Safari', 60, 38, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (23, 'Zoo', 84, 23, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (24, 'Safari', 37, 81, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (25, 'Night Tour', 97, 75, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (26, 'Movie', 74, 20, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (27, 'Safari', 61, 65, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (28, 'Safari', 35, 75, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (29, 'Movie', 65, 52, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (30, 'Kids', 34, 95, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (31, 'Movie', 87, 62, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (32, 'Safari', 61, 91, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (33, 'Zoo', 46, 80, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (34, 'Night Tour', 75, 91, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (35, 'Movie', 32, 69, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (36, 'Movie', 100, 62, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (37, 'Movie', 23, 78, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (38, 'Kids', 68, 29, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (39, 'Safari', 78, 44, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (40, 'Safari', 20, 83, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (41, 'Movie', 67, 32, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (42, 'Kids', 58, 68, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (43, 'Zoo', 61, 55, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (44, 'Safari', 65, 98, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (45, 'Movie', 20, 32, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (46, 'Kids', 93, 15, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (47, 'Movie', 68, 37, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (48, 'Kids', 81, 25, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (49, 'Movie', 58, 33, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (50, 'Zoo', 20, 67, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (51, 'Night Tour', 26, 14, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (52, 'Movie', 21, 61, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (53, 'Zoo', 46, 53, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (54, 'Kids', 74, 70, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (55, 'Zoo', 99, 63, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (56, 'Zoo', 82, 95, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (57, 'Zoo', 81, 88, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (58, 'Zoo', 28, 30, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (59, 'Zoo', 37, 36, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (60, 'Zoo', 36, 68, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (61, 'Zoo', 54, 30, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (62, 'Night Tour', 36, 61, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (63, 'Zoo', 35, 52, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (64, 'Safari', 85, 17, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (65, 'Safari', 81, 33, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (66, 'Zoo', 74, 28, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (67, 'Kids', 100, 49, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (68, 'Kids', 52, 74, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (69, 'Movie', 24, 54, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (70, 'Movie', 89, 25, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (71, 'Movie', 79, 67, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (72, 'Kids', 92, 40, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (73, 'Safari', 46, 61, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (74, 'Safari', 35, 65, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (75, 'Safari', 50, 60, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (76, 'Zoo', 49, 38, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (77, 'Night Tour', 59, 52, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (78, 'Safari', 98, 81, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (79, 'Night Tour', 27, 100, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (80, 'Movie', 57, 50, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (81, 'Night Tour', 57, 71, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (82, 'Kids', 49, 76, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (83, 'Movie', 99, 60, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (84, 'Kids', 38, 99, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (85, 'Safari', 46, 71, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (86, 'Movie', 81, 43, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (87, 'Night Tour', 40, 33, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (88, 'Zoo', 84, 98, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (89, 'Night Tour', 72, 67, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (90, 'Safari', 36, 85, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (91, 'Night Tour', 99, 36, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (92, 'Movie', 54, 42, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (93, 'Zoo', 68, 38, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (94, 'Safari', 76, 53, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (95, 'Movie', 80, 82, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (96, 'Kids', 70, 46, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (97, 'Safari', 59, 51, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (98, 'Night Tour', 21, 90, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (99, 'Night Tour', 55, 87, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (100, 'Kids', 21, 37, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (101, 'Safari', 37, 97, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (102, 'Kids', 91, 54, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (103, 'Zoo', 54, 42, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (104, 'Safari', 64, 49, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (105, 'Zoo', 82, 95, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (106, 'Safari', 75, 35, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (107, 'Kids', 89, 70, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (108, 'Night Tour', 91, 93, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (109, 'Movie', 33, 61, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (110, 'Movie', 21, 68, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (111, 'Safari', 64, 36, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (112, 'Movie', 45, 58, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (113, 'Kids', 42, 52, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (114, 'Movie', 49, 47, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (115, 'Movie', 64, 31, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (116, 'Night Tour', 96, 69, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (117, 'Movie', 77, 73, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (118, 'Safari', 28, 98, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (119, 'Zoo', 83, 12, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (120, 'Kids', 28, 47, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (121, 'Safari', 65, 91, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (122, 'Zoo', 76, 28, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (123, 'Kids', 69, 73, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (124, 'Zoo', 83, 67, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (125, 'Kids', 53, 16, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (126, 'Movie', 54, 90, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (127, 'Night Tour', 67, 10, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (128, 'Zoo', 42, 98, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (129, 'Night Tour', 20, 16, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (130, 'Kids', 65, 71, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (131, 'Kids', 29, 68, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (132, 'Safari', 32, 35, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (133, 'Movie', 84, 20, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (134, 'Night Tour', 39, 39, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (135, 'Safari', 43, 37, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (136, 'Night Tour', 60, 51, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (137, 'Safari', 51, 47, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (138, 'Safari', 62, 97, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (139, 'Movie', 62, 18, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (140, 'Movie', 36, 38, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (141, 'Safari', 38, 13, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (142, 'Night Tour', 66, 47, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (143, 'Movie', 46, 49, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (144, 'Zoo', 35, 28, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (145, 'Zoo', 68, 47, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (146, 'Safari', 98, 27, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (147, 'Zoo', 82, 59, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (148, 'Safari', 97, 94, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (149, 'Safari', 49, 51, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (150, 'Night Tour', 51, 85, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (151, 'Zoo', 98, 54, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (152, 'Kids', 83, 43, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (153, 'Night Tour', 31, 38, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (154, 'Safari', 48, 98, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (155, 'Safari', 85, 56, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (156, 'Night Tour', 39, 100, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (157, 'Kids', 57, 96, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (158, 'Kids', 70, 26, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (159, 'Night Tour', 56, 20, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (160, 'Safari', 70, 21, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (161, 'Zoo', 93, 99, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (162, 'Movie', 54, 83, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (163, 'Safari', 54, 16, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (164, 'Movie', 87, 79, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (165, 'Zoo', 71, 51, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (166, 'Safari', 23, 72, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (167, 'Zoo', 71, 64, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (168, 'Movie', 52, 77, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (169, 'Zoo', 100, 47, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (170, 'Movie', 52, 38, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (171, 'Zoo', 96, 35, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (172, 'Zoo', 36, 56, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (173, 'Night Tour', 22, 85, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (174, 'Night Tour', 73, 74, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (175, 'Movie', 31, 43, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (176, 'Kids', 43, 62, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (177, 'Night Tour', 37, 48, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (178, 'Night Tour', 87, 19, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (179, 'Safari', 61, 72, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (180, 'Movie', 85, 85, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (181, 'Night Tour', 79, 47, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (182, 'Kids', 33, 77, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (183, 'Safari', 71, 42, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (184, 'Zoo', 47, 47, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (185, 'Safari', 74, 89, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (186, 'Safari', 66, 38, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (187, 'Night Tour', 32, 66, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (188, 'Kids', 21, 48, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (189, 'Zoo', 46, 64, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (190, 'Zoo', 33, 93, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (191, 'Movie', 35, 64, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (192, 'Kids', 98, 43, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (193, 'Zoo', 55, 39, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (194, 'Night Tour', 83, 45, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (195, 'Kids', 68, 85, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (196, 'Night Tour', 23, 21, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (197, 'Kids', 32, 25, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (198, 'Safari', 68, 68, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (199, 'Kids', 57, 26, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (200, 'Kids', 89, 34, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (201, 'Zoo', 24, 76, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (202, 'Zoo', 45, 73, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (203, 'Zoo', 30, 50, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (204, 'Kids', 55, 35, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (205, 'Safari', 86, 67, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (206, 'Zoo', 51, 46, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (207, 'Movie', 70, 43, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (208, 'Night Tour', 36, 98, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (209, 'Movie', 24, 63, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (210, 'Movie', 75, 15, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (211, 'Movie', 74, 83, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (212, 'Zoo', 55, 56, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (213, 'Safari', 26, 86, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (214, 'Movie', 91, 81, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (215, 'Movie', 25, 81, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (216, 'Movie', 36, 18, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (217, 'Safari', 44, 48, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (218, 'Zoo', 21, 19, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (219, 'Safari', 85, 23, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (220, 'Movie', 37, 33, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (221, 'Night Tour', 67, 82, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (222, 'Kids', 42, 51, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (223, 'Kids', 77, 87, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (224, 'Night Tour', 37, 57, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (225, 'Zoo', 33, 53, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (226, 'Movie', 89, 52, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (227, 'Zoo', 20, 89, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (228, 'Night Tour', 97, 52, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (229, 'Movie', 54, 88, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (230, 'Safari', 23, 76, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (231, 'Night Tour', 56, 23, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (232, 'Kids', 61, 99, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (233, 'Kids', 49, 30, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (234, 'Movie', 84, 38, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (235, 'Zoo', 60, 88, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (236, 'Zoo', 67, 14, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (237, 'Night Tour', 21, 23, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (238, 'Night Tour', 83, 98, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (239, 'Safari', 36, 55, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (240, 'Kids', 100, 89, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (241, 'Movie', 49, 51, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (242, 'Zoo', 63, 39, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (243, 'Movie', 50, 35, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (244, 'Safari', 50, 75, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (245, 'Night Tour', 52, 85, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (246, 'Night Tour', 67, 67, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (247, 'Night Tour', 68, 44, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (248, 'Safari', 97, 13, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (249, 'Zoo', 29, 38, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (250, 'Movie', 66, 80, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (251, 'Safari', 92, 15, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (252, 'Movie', 43, 20, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (253, 'Night Tour', 22, 53, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (254, 'Night Tour', 87, 59, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (255, 'Movie', 41, 79, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (256, 'Movie', 21, 88, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (257, 'Movie', 58, 26, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (258, 'Night Tour', 23, 49, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (259, 'Safari', 61, 96, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (260, 'Safari', 65, 64, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (261, 'Kids', 69, 24, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (262, 'Safari', 58, 86, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (263, 'Kids', 62, 54, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (264, 'Safari', 27, 23, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (265, 'Movie', 25, 59, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (266, 'Night Tour', 96, 20, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (267, 'Safari', 42, 27, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (268, 'Safari', 27, 39, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (269, 'Zoo', 94, 61, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (270, 'Safari', 85, 67, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (271, 'Safari', 57, 16, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (272, 'Night Tour', 74, 56, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (273, 'Zoo', 23, 38, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (274, 'Kids', 56, 88, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (275, 'Zoo', 50, 56, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (276, 'Kids', 25, 20, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (277, 'Kids', 58, 81, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (278, 'Safari', 52, 38, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (279, 'Night Tour', 33, 85, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (280, 'Safari', 56, 29, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (281, 'Kids', 97, 100, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (282, 'Zoo', 21, 53, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (283, 'Zoo', 24, 43, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (284, 'Kids', 98, 83, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (285, 'Night Tour', 34, 80, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (286, 'Zoo', 90, 71, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (287, 'Night Tour', 100, 55, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (288, 'Movie', 97, 78, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (289, 'Kids', 55, 20, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (290, 'Night Tour', 84, 90, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (291, 'Kids', 48, 25, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (292, 'Safari', 21, 22, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (293, 'Night Tour', 100, 31, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (294, 'Zoo', 48, 96, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (295, 'Zoo', 37, 41, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (296, 'Zoo', 63, 95, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (297, 'Movie', 68, 13, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (298, 'Kids', 79, 71, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (299, 'Safari', 44, 91, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (300, 'Safari', 28, 40, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (301, 'Zoo', 50, 24, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (302, 'Night Tour', 77, 23, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (303, 'Movie', 51, 41, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (304, 'Zoo', 56, 87, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (305, 'Zoo', 61, 91, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (306, 'Night Tour', 85, 81, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (307, 'Kids', 95, 29, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (308, 'Zoo', 73, 13, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (309, 'Zoo', 47, 34, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (310, 'Zoo', 87, 31, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (311, 'Kids', 96, 83, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (312, 'Safari', 83, 49, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (313, 'Safari', 56, 33, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (314, 'Kids', 28, 18, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (315, 'Safari', 97, 56, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (316, 'Movie', 47, 27, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (317, 'Movie', 100, 52, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (318, 'Night Tour', 84, 88, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (319, 'Zoo', 23, 72, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (320, 'Zoo', 80, 14, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (321, 'Night Tour', 96, 42, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (322, 'Night Tour', 31, 77, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (323, 'Night Tour', 83, 51, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (324, 'Kids', 47, 72, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (325, 'Zoo', 75, 79, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (326, 'Zoo', 75, 81, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (327, 'Zoo', 82, 95, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (328, 'Zoo', 66, 95, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (329, 'Kids', 98, 74, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (330, 'Zoo', 78, 71, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (331, 'Movie', 62, 66, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (332, 'Kids', 92, 40, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (333, 'Zoo', 23, 25, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (334, 'Zoo', 53, 54, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (335, 'Safari', 69, 62, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (336, 'Kids', 92, 51, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (337, 'Movie', 94, 21, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (338, 'Night Tour', 34, 67, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (339, 'Movie', 95, 48, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (340, 'Night Tour', 75, 35, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (341, 'Kids', 79, 63, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (342, 'Night Tour', 40, 43, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (343, 'Zoo', 66, 39, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (344, 'Night Tour', 39, 62, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (345, 'Kids', 74, 65, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (346, 'Zoo', 87, 58, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (347, 'Movie', 22, 89, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (348, 'Zoo', 78, 58, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (349, 'Kids', 22, 96, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (350, 'Zoo', 51, 83, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (351, 'Kids', 52, 17, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (352, 'Zoo', 57, 83, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (353, 'Night Tour', 51, 65, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (354, 'Safari', 78, 71, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (355, 'Movie', 34, 82, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (356, 'Zoo', 33, 17, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (357, 'Zoo', 92, 87, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (358, 'Movie', 68, 49, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (359, 'Night Tour', 98, 94, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (360, 'Zoo', 27, 55, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (361, 'Kids', 80, 82, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (362, 'Safari', 36, 88, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (363, 'Night Tour', 43, 41, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (364, 'Safari', 20, 73, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (365, 'Movie', 35, 28, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (366, 'Safari', 64, 36, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (367, 'Night Tour', 92, 96, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (368, 'Movie', 33, 64, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (369, 'Night Tour', 88, 25, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (370, 'Movie', 73, 11, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (371, 'Movie', 34, 87, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (372, 'Zoo', 59, 48, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (373, 'Movie', 60, 76, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (374, 'Safari', 57, 95, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (375, 'Safari', 37, 15, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (376, 'Safari', 24, 86, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (377, 'Movie', 49, 73, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (378, 'Kids', 40, 26, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (379, 'Night Tour', 20, 29, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (380, 'Zoo', 71, 59, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (381, 'Zoo', 91, 29, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (382, 'Zoo', 100, 48, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (383, 'Night Tour', 74, 78, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (384, 'Night Tour', 29, 53, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (385, 'Night Tour', 100, 70, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (386, 'Movie', 25, 43, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (387, 'Night Tour', 30, 32, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (388, 'Zoo', 79, 59, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (389, 'Safari', 84, 40, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (390, 'Night Tour', 89, 94, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (391, 'Zoo', 94, 98, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (392, 'Night Tour', 79, 51, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (393, 'Movie', 78, 57, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (394, 'Kids', 81, 96, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (395, 'Movie', 75, 38, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (396, 'Night Tour', 60, 30, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (397, 'Zoo', 26, 22, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (398, 'Kids', 69, 25, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (399, 'Kids', 28, 58, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (400, 'Kids', 54, 87, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (401, 'Night Tour', 23, 84, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (402, 'Safari', 22, 100, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (403, 'Movie', 56, 47, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (404, 'Safari', 52, 39, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (405, 'Safari', 89, 48, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (406, 'Zoo', 30, 82, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (407, 'Night Tour', 27, 42, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (408, 'Kids', 82, 74, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (409, 'Safari', 24, 51, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (410, 'Night Tour', 89, 66, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (411, 'Zoo', 47, 62, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (412, 'Night Tour', 20, 19, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (413, 'Night Tour', 95, 38, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (414, 'Kids', 90, 94, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (415, 'Zoo', 88, 99, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (416, 'Night Tour', 47, 27, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (417, 'Zoo', 23, 23, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (418, 'Kids', 88, 49, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (419, 'Zoo', 63, 11, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (420, 'Movie', 74, 15, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (421, 'Zoo', 55, 70, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (422, 'Safari', 88, 42, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (423, 'Safari', 93, 97, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (424, 'Movie', 67, 80, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (425, 'Zoo', 72, 14, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (426, 'Night Tour', 46, 48, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (427, 'Kids', 30, 16, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (428, 'Movie', 83, 16, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (429, 'Zoo', 58, 94, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (430, 'Safari', 62, 88, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (431, 'Movie', 72, 76, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (432, 'Night Tour', 29, 45, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (433, 'Kids', 91, 100, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (434, 'Kids', 100, 91, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (435, 'Night Tour', 78, 59, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (436, 'Night Tour', 40, 43, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (437, 'Night Tour', 62, 98, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (438, 'Movie', 49, 10, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (439, 'Zoo', 84, 60, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (440, 'Night Tour', 91, 19, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (441, 'Movie', 71, 78, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (442, 'Movie', 39, 66, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (443, 'Night Tour', 56, 18, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (444, 'Safari', 32, 60, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (445, 'Safari', 52, 24, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (446, 'Night Tour', 47, 13, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (447, 'Movie', 79, 59, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (448, 'Safari', 35, 40, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (449, 'Zoo', 88, 36, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (450, 'Kids', 60, 99, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (451, 'Movie', 25, 60, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (452, 'Night Tour', 97, 50, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (453, 'Movie', 44, 89, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (454, 'Night Tour', 96, 51, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (455, 'Kids', 27, 31, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (456, 'Kids', 24, 83, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (457, 'Night Tour', 72, 13, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (458, 'Kids', 51, 56, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (459, 'Safari', 87, 67, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (460, 'Movie', 74, 68, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (461, 'Kids', 92, 100, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (462, 'Safari', 48, 10, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (463, 'Safari', 98, 60, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (464, 'Safari', 28, 96, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (465, 'Kids', 33, 93, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (466, 'Safari', 98, 46, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (467, 'Safari', 51, 15, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (468, 'Night Tour', 45, 17, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (469, 'Night Tour', 57, 38, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (470, 'Movie', 75, 87, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (471, 'Zoo', 84, 79, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (472, 'Zoo', 47, 72, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (473, 'Movie', 58, 74, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (474, 'Safari', 48, 73, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (475, 'Kids', 25, 30, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (476, 'Night Tour', 84, 63, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (477, 'Kids', 61, 55, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (478, 'Movie', 57, 29, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (479, 'Night Tour', 70, 46, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (480, 'Kids', 94, 97, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (481, 'Night Tour', 28, 24, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (482, 'Kids', 37, 55, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (483, 'Zoo', 34, 74, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (484, 'Safari', 79, 23, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (485, 'Kids', 29, 57, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (486, 'Kids', 64, 88, 'Night');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (487, 'Safari', 77, 63, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (488, 'Kids', 97, 93, 'Family');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (489, 'Night Tour', 54, 10, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (490, 'Safari', 73, 92, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (491, 'Kids', 40, 98, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (492, 'Safari', 99, 81, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (493, 'Movie', 56, 59, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (494, 'Kids', 62, 56, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (495, 'Safari', 73, 80, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (496, 'Zoo', 52, 69, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (497, 'Safari', 35, 10, 'Education');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (498, 'Safari', 63, 94, 'Animal');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (499, 'Movie', 92, 85, 'Adventure');
insert into ticket_types (Ticket_ID, Ticket_Name, Max_Capacity, Base_Price, Category) values (500, 'Kids', 23, 83, 'Night');
